steps: 
# terraform init
- name: hashicorp/terraform:light
  entrypoint: 'sh'
  args: 
    - '-c'
    - |
      cd /workspace/working-modules
      terraform init
 # terraform plan 
- name: hashicorp/terraform:light
  entrypoint: 'sh'
  args: 
    - '-c'
    - |
      cd /workspace/working-modules
      terraform plan -out=tfplan     
options:
 logging: CLOUD_LOGGING_ONLY  